<?php
namespace DIC\DicoBundle\Repository;

/**
 * countriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class wordsRepository extends \Doctrine\ORM\EntityRepository
{
}
